PTBR
ChuckTheSheep/zomboid-cnd-speech pull request #23
Opened 2021-05-04 07:19 UTC by renkien

Translated to PT-BR . Yet having a few problems with CHARSET.

2021-05-04 13:14 UTC, ChuckTheSheep requested changes
Thank you for the translation! There are some minor format issues with spaces and punctuation. 

If the accents are giving you issues the text file needs to be encoded in `windows-1252`. If you're not sure how to do that I can.

2021-05-04 13:14 UTC, ChuckTheSheep commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_Drunk2 = "ooooobaaaa,agora vai! *soluçando*",
You can't mix *gestures* with speech on the same line. I would make `*soluçando*` it's own drunk phrase. Also, be careful of the lack of space after the comma (,).

2021-05-04 13:14 UTC, ChuckTheSheep commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_HasACold3 = "Eu gripei,certeza..",
Careful with not having a space after commas or periods.

2021-05-04 13:14 UTC, ChuckTheSheep commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_OutOfAmmo4 = "*Sem balas!",
Shouldn't have a * here, unless this is an accent issue.

2021-05-04 15:46 UTC, renkien commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_Drunk1 = "estou me sentindo embriagado(a).",
No,in portuguese we have genres for these words,this is why it sometimes make it difficult to translate a few things. Same happened to the ''fuck'' translation since in english it is used to almost everything haha.

2021-05-04 15:47 UTC, renkien commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_Drunk2 = "ooooobaaaa,agora vai! *soluçando*",
Got it,i'll change it right away.

2021-05-04 16:58 UTC, renkien commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_HasACold3 = "Eu gripei,certeza..",
Fixed it.

2021-05-04 16:58 UTC, renkien commented on Contents/mods/zomboid-cnd-speech/media/lua/shared/Translate/PTBR/UI_PTBR
> +UI_Phrases_OutOfAmmo4 = "*Sem balas!",
Removed it. Also enconded in windows 1252 as you said and tested,it fixed the problem.

2021-05-05 00:30 UTC, merged

2021-05-05 03:08 UTC, ChuckTheSheep commented
Let me know if the accents look correct.